# Generated by Django 6.0.5 on 2026-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
